FROM node:23 AS base
WORKDIR /app

FROM base AS dep
COPY package.json package-lock.json ./
RUN npm i 

FROM base AS build
COPY --from=dep /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM node:23-alpine AS production
WORKDIR /app
COPY --from=dep /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist
EXPOSE 3000
CMD ["npm", "run", "start:prod"]
